### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by 520rahul** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#11]
Can v install exe file i.e GUI VERSION IN WINDOWS 7. Any additional requirements to b fulfilled??

**Comment by 520rahul** [comment]
@divagicha

**Comment by divagicha** [comment]
The exe file has been built to be standalone, which means everything is packed into it, even the python itself. So you don't need anything else to be done first, before installing the exe. Although I haven't dont much checking for the specific win 7 OS, but it should go through easily, installation and running. Let me know if still any error arises, I'll do the changes accordingly. Cheers! :)

**Comment by 520rahul** [comment]
Thanks
