### ISSUE TITLE
Not running on my pc

### ISSUE THREAD

**Issue by 520rahul** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#12]
@divagicha when i try to tun on my pc this error shows : the program cant start because api-ms-win-core-path-1-1.0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

I have reinstalled it many times and still not working

**Comment by divagicha** [comment]
Can you please tell something more about the error. What OS you are running? it's architecture (32 or 64-bit)? Did you use exe file or the script version?

**Comment by 520rahul** [comment]
> Can you please tell something more about the error. What OS you are running? it's architecture (32 or 64-bit)? Did you use exe file or the script version?

@divagicha I m using windows 7 ultimate 64 bit version. I used both exe and script but same error both time

**Comment by divagicha** [comment]
which python version did you install for running the script?

**Comment by 520rahul** [comment]
> which python version did you install for running the script?

Python 3.8.10

**Comment by Coy-sys1** [comment]
After you enter the Mobile Number the Script closes. Maybe there has been an update from the COWIN server side

**Comment by Coy-sys1** [comment]
Try running the script after few minutes it should work

**Comment by divagicha** [comment]
Okay. This script was made using python 3.9. Moreover, I'll check running the script on windows 7 and let you know what might have arised the issue on your system..

**Comment by 520rahul** [comment]
> Okay. This script was made using python 3.9. Moreover, I'll check running the script on windows 7 and let you know what might have arised the issue on your system..

Thanks brother. Waiting for ur reply

**Comment by divagicha** [comment]
> After you enter the Mobile Number the Script closes. Maybe there has been an update from the COWIN server side

@Coy-sys1 Closing of script after entering mobile number indicates some misconfiguration in the script itself. Can you share the screenshot of the same, as to what error is being generated before the script closes?

**Comment by divagicha** [comment]
@520rahul if you google for the error that you are facing in win 7 64-bit, there is a [link](https://bugs.python.org/issue41412#msg374411) in the top results which clearly states **"Microsoft ended extended support for Windows 7 back in January of this year, so Python 3.9 does not support Windows 7, in accordance with PEP 11 [1]"**. So, I guess you have no other option but to upgrade your windows as this program has been written using python3.9

**Comment by 520rahul** [comment]
> @520rahul if you google for the error that you are facing in win 7 64-bit, there is a [link](https://bugs.python.org/issue41412#msg374411) in the top results which clearly states **"Microsoft ended extended support for Windows 7 back in January of this year, so Python 3.9 does not support Windows 7, in accordance with PEP 11 [1]"**. So, I guess you have no other option but to upgrade your windows as this program has been written using python3.9

Thank u so much brother
