### ISSUE TITLE
Can you add an option for selecting paid or free vaccine

### ISSUE THREAD

**Issue by saihivarkar** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#13]
Hi! Hope you are doing well?
As the central govt has started with free vaccination alongside private players, can you add an additional option to select between free or paid vaccine?
Thank you in advance!

**Comment by divagicha** [comment]
Sure, I'll add that feature in near future. Right now, due to my current job routine I don't get enough time to make and test necessary updations, but you can hope to see that feature soon...
