### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by sunilgoudar** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#2]
Hi, i want to ask... the capatcha is auto submitted or we have to enter manually.

**Comment by divagicha** [comment]
Captcha, as of now, comes up in a pop-up window once a valid centre is found based on your entered preferences. User has to hit 'Submit' after entering the captcha, upon which request is further processed by the script and the desired slot is booked.

**Comment by sunilgoudar** [comment]
Okay thanks for the quick reply.
