### ISSUE TITLE
Mobile number starting with 6 is not accepting

### ISSUE THREAD

**Issue by ansi82** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#4]

**Comment by divagicha** [comment]
Thank you for pointing this out. The program was doing a basic regex match for validating the mobile number. I've updated the code and it will now accept mobile numbers starting with '6' as well.

Kindly download the zip again and re-run the script. Let me know if it works for you now.

**Comment by ansi82** [comment]
thanks solved
