### ISSUE TITLE
removal of CAPTCHA

### ISSUE THREAD

**Issue by saihivarkar** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#8]
Hi! Thank you for developing this tool. As you must be aware that recently GOI has limited API searches to 20 and have removed mandatory CAPTCHA for slot booking (https://www.republicworld.com/technology-news/other-tech-news/cowin-does-away-with-captcha-check-registration-for-covid-vaccination-to-become-quicker.html). So can you modify the tool to get rid of CAPTCHA?

**Comment by divagicha** [comment]
Yes sure @saihivarkar ad thanks for pointing this out. I'm aware of the changes introduced by GOI but due to some other urgent projects in the schedule I've not been able to publish the updated changes yet. Once tested, I will update the changes on git repo as well, ASAP!!

**Comment by saihivarkar** [comment]
Best wishes for your projects!
And lastly, you are doing a wonderful job by developing such a tool. I have been using this tool to book slots for many underprivileged people. A big thanks to you!

**Comment by divagicha** [comment]
Glad to know it could make a difference, because only for this very purpose it has been developed. Also, I've updated the code and binary on github with captcha removal changes. You too keep up the good work of helping others. Cheers!

**Comment by saihivarkar** [comment]
Thank you for the update @divagicha 
Hats off to your meritorious work!
