### ISSUE TITLE
Can we have vaccine type selection function in the tool?

### ISSUE THREAD

**Issue by saihivarkar** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#9]
Hi @divagicha 
It's not an issue to be raised but to enhance the usability of this tool, I am raising this point. Can you also put an additional option of vaccine-type selection? I presume after 21st June, there will be centers injecting all vaccine types. So, I think putting an additional option for vaccine-type selection would be beneficial to the user!
What's your thought on this?

**Comment by divagicha** [comment]
Sure, with changes being implemented everyday there might be availability of more than one type of vaccine at the centres. You can find this option of 'selecting vaccine type' in future upgradation of the script. Thanks!

**Comment by divagicha** [comment]
I've now updated the scripts to get vaccine preference from the user, before proceeding to check for available centres. Will add more vaccine options as and when new vaccine gets available to book on the official platform.

**Comment by saihivarkar** [comment]
Thank you for the efforts @divagicha !
